;;; SPDX-License-Identifier: GPL-3.0-or-later
;;; Written-score export. Durations and positions stay exact until XML output.
(use-modules (srfi srfi-1) (sxml simple))

(define (wmx:property music name . fallback)
  (ly:music-property music name (if (null? fallback) '() (car fallback))))
(define (wmx:name music) (wmx:property music 'name))
(define (wmx:children music)
  (let ((element (wmx:property music 'element)))
    (if (ly:music? element) (list element) (wmx:property music 'elements))))
(define (wmx:quarters duration)
  (* 4 (expt 2 (- (ly:duration-log duration)))
     (- 2 (expt 2 (- (ly:duration-dot-count duration))))
     (ly:duration-scale duration)))
(define (wmx:fail message . args)
  (apply ly:error (string-append "MusicXML export: " message) args))
(define (wmx:text value) (format #f "~a" value))
(define (wmx:node tag value) (list tag (wmx:text value)))

;; A PianoStaff/GrandStaff is one part. Other staves are separate parts.
(define (wmx:parts music)
  (if (and (eq? (wmx:name music) 'ContextSpeccedMusic)
           (memq (wmx:property music 'context-type)
                 '(Staff PianoStaff GrandStaff)))
      (list music)
      (let* ((children (wmx:children music))
             (groups (map wmx:parts children))
             (parts (append-map identity groups)))
        (unless (null? parts)
          (unless (and (every pair? groups)
                       (memq (wmx:name music) '(ContextSpeccedMusic SimultaneousMusic
                                               SequentialMusic RelativeOctaveMusic UnrelativableMusic TransposedMusic))
                       (or (not (eq? (wmx:name music) 'SequentialMusic)) (= (length children) 1)))
            (wmx:fail "music outside parallel part contexts is not supported"))
          (when (eq? (wmx:name music) 'ContextSpeccedMusic)
            (unless (and (memq (wmx:property music 'context-type) '(Score StaffGroup))
                         (null? (wmx:property music 'property-operations)))
              (wmx:fail "unsupported part-group context or settings"))))
        parts)))

;; Events: #(position duration kind payload staff voice). Collectors keep all
;; score semantics here; the serializer knows nothing about LilyPond syntax.
(define (wmx:collect music)
  (let ((events '()) (staff-count 0) (staff-ids '()) (repeat-depth 0))
    (define (emit pos dur kind data staff voice)
      (set! events (cons (vector pos dur kind data staff voice) events)))
    (define (new-staff id)
      (let ((known (and (not (string-null? id)) (assoc id staff-ids))))
        (if known (cdr known)
            (begin
              (set! staff-count (+ staff-count 1))
              (set! staff-ids (acons id staff-count staff-ids))
              staff-count))))
    (define (walk m pos staff voice)
      (let ((name (wmx:name m)) (children (wmx:children m)))
        (case name
          ((SequentialMusic)
           (fold (lambda (child next) (walk child next staff voice)) pos children))
          ((SimultaneousMusic)
           (let ((index 0))
             (fold (lambda (child end)
                     (set! index (+ index 1))
                     (max end (walk child pos staff
                                (if (= index 1) voice
                                    (format #f "~a.~a" voice index)))))
                   pos children)))
          ((ContextSpeccedMusic)
           (let* ((type (wmx:property m 'context-type))
                  (id (wmx:property m 'context-id ""))
                  (created (wmx:property m 'create-new #f))
                  (target (if (and (eq? type 'Staff) (or created (= staff 0)))
                              (new-staff id) staff)))
             (unless (memq type '(Score Timing Staff Voice PianoStaff GrandStaff StaffGroup))
               (wmx:fail "unsupported context ~a" type))
             (unless (null? (wmx:property m 'property-operations))
               (wmx:fail "context settings (\\with) need an explicit export mapping"))
             (walk (car children) pos target
               (cond ((not (= target staff)) (format #f "s~a" target))
                     ((and (eq? type 'Voice) (not (string-null? id))) id)
                     (else voice)))))
          ((RelativeOctaveMusic UnrelativableMusic TimeScaledMusic TransposedMusic)
           ;; LilyPond has already resolved pitches and scaled leaf durations.
           (walk (car children) pos staff voice))
          ((VoltaRepeatedMusic)
           (when (> repeat-depth 0) (wmx:fail "nested volta repeats are not supported yet"))
           (unless (null? (wmx:property m 'elements))
             (wmx:fail "repeat alternatives are not supported yet"))
           (emit pos 0 'repeat '(forward) staff voice)
           (set! repeat-depth (+ repeat-depth 1))
           (let ((end (walk (wmx:property m 'element) pos staff voice)))
             (set! repeat-depth (- repeat-depth 1))
             (emit end 0 'repeat
               (list 'backward (wmx:property m 'repeat-count)) staff voice)
             end))
          ((UnfoldedRepeatedMusic)
           (unless (null? (wmx:property m 'elements))
             (wmx:fail "unfolded repeat alternatives are not supported yet"))
           (fold (lambda (_ next) (walk (wmx:property m 'element) next staff voice))
                 pos (iota (wmx:property m 'repeat-count))))
          ((NoteEvent RestEvent SkipEvent MultiMeasureRestMusic)
           (let* ((duration (wmx:property m 'duration))
                  (length (wmx:quarters duration)))
             (when (<= length 0) (wmx:fail "non-positive note duration"))
             (emit pos length (if (eq? name 'NoteEvent) 'note
                                  (if (eq? name 'SkipEvent) 'skip 'rest))
                   (list m (wmx:property m 'articulations)) staff voice)
             (+ pos length)))
          ((EventChord)
           (let* ((notes (filter (lambda (c) (memq (wmx:name c) '(NoteEvent RestEvent)))
                                 children))
                  (marks (remove (lambda (c) (memq (wmx:name c) '(NoteEvent RestEvent)))
                                 children)))
             (if (null? notes)
                 (begin (for-each (lambda (c) (walk c pos staff voice)) marks) pos)
                 (let ((length (wmx:quarters (wmx:property (car notes) 'duration))))
                   (for-each
                     (lambda (note)
                       (unless (= length (wmx:quarters (wmx:property note 'duration)))
                         (wmx:fail "chord members have different durations"))
                       (emit pos length (if (eq? (wmx:name note) 'RestEvent) 'rest 'note)
                         (list note (append (wmx:property note 'articulations) marks))
                         staff voice)) notes)
                   (+ pos length)))))
          ((ReferenceTimeSignatureMusic)
           (emit pos 0 'TimeSignatureMusic m staff voice) pos)
          ((TimeSignatureMusic KeyChangeEvent TempoChangeEvent PartialSet)
           (emit pos 0 name m staff voice) pos)
          ((AbsoluteDynamicEvent CrescendoEvent DecrescendoEvent SustainEvent)
           (emit pos 0 'direction m staff voice) pos)
          ((PropertySet)
           (let ((symbol (wmx:property m 'symbol)))
             (unless (memq symbol '(clefGlyph clefPosition middleCClefPosition
                                   clefTransposition clefTranspositionStyle
                                   tempoWholesPerMinute autoBeaming stemDirection
                                   restPosition slurDirection tieDirection
                                   dotDirection beamPositions))
               (wmx:fail "unsupported context property ~a" symbol))
             (when (and (eq? symbol 'clefTransposition)
                        (not (zero? (wmx:property m 'value))))
               (wmx:fail "octave-transposing clefs are not supported yet"))
             (when (eq? symbol 'clefGlyph)
               (emit pos 0 'clef (cons (wmx:property m 'value) #f) staff voice))
             (when (eq? symbol 'clefPosition)
               (let ((event (find (lambda (e) (and (eq? (vector-ref e 2) 'clef)
                                                   (= pos (vector-ref e 0))
                                                   (= staff (vector-ref e 4)))) events)))
                 (unless event (wmx:fail "clef position without a clef"))
                 (set-cdr! (vector-ref event 3) (/ (+ 6 (wmx:property m 'value)) 2))))) pos)
          ((ApplyContext)
           (unless (eq? (wmx:property m 'procedure) ly:set-middle-C!)
             (wmx:fail "custom context functions are not supported")) pos)
          ((OverrideProperty RevertProperty BarCheck BarCheckEvent BarLineEvent
            LineBreakEvent PageBreakEvent PageTurnEvent BeamEvent)
           pos)
          (else (wmx:fail "unsupported music ~a" name)))))
    (let ((end (walk music 0 0 "1")))
      (when (zero? staff-count) (set! staff-count 1))
      (for-each (lambda (e) (when (zero? (vector-ref e 4)) (vector-set! e 4 1))) events)
      (list (stable-sort (reverse events) (lambda (a b) (< (vector-ref a 0) (vector-ref b 0))))
            end staff-count))))

(define (wmx:meter event)
  (let* ((m (vector-ref event 3))
         (meter (if (eq? (wmx:name m) 'ReferenceTimeSignatureMusic)
                    (wmx:property m 'time-signature)
                    (cons (wmx:property m 'numerator) (wmx:property m 'denominator)))))
    (unless (and (pair? meter) (integer? (car meter)) (integer? (cdr meter))
                 (> (car meter) 0) (> (cdr meter) 0))
      (wmx:fail "unsupported compound time signature"))
    meter))

;; Use one bar grid for every part; conflicting meters fail rather than drift.
(define (wmx:measures events end)
  (let* ((meters (filter (lambda (e) (eq? (vector-ref e 2) 'TimeSignatureMusic)) events))
         (pickups (filter (lambda (e) (eq? (vector-ref e 2) 'PartialSet)) events))
         (pickup (and (pair? pickups)
                      (wmx:quarters (wmx:property (vector-ref (car pickups) 3) 'duration)))))
    (for-each (lambda (e)
                (unless (and (zero? (vector-ref e 0))
                             (= pickup (wmx:quarters (wmx:property (vector-ref e 3) 'duration))))
                  (wmx:fail "conflicting or mid-score partial measures"))) pickups)
    (let loop ((pos 0) (meter '(4 . 4)) (bars '()))
      (if (>= pos end) (reverse bars)
          (let* ((changes (filter (lambda (e) (= pos (vector-ref e 0))) meters))
                 (current (if (null? changes) meter (wmx:meter (car changes))))
                 (length (if (and (zero? pos) pickup) pickup
                             (* 4 (/ (car current) (cdr current)))))
                 (next (min end (+ pos length))))
            (for-each (lambda (e) (unless (equal? current (wmx:meter e))
                                   (wmx:fail "conflicting time signatures"))) changes)
            (when (any (lambda (e) (< pos (vector-ref e 0) next)) meters)
              (wmx:fail "time signature change inside a measure"))
            (when (<= length 0) (wmx:fail "non-positive measure length"))
            (when (> length (* 4 (/ (car current) (cdr current))))
              (wmx:fail "pickup is longer than the measure"))
            (loop next current
              (cons (list pos next current
                          (or (and (zero? pos) pickup)
                              (< (- next pos) (* 4 (/ (car current) (cdr current)))))) bars)))))))

(define (wmx:key music staff)
  (let* ((alterations (wmx:property music 'pitch-alist))
         (fifths (* 2 (apply + (map cdr alterations))))
         (tonic (wmx:property music 'tonic)))
    (unless (and (integer? fifths) (<= -7 fifths 7))
      (wmx:fail "nonstandard key signature"))
    (let ((changed (take (if (negative? fifths) '(6 2 5 1 4 0 3) '(3 0 4 1 5 2 6)) (abs fifths))))
      (for-each (lambda (step)
                  (unless (= (assoc-get step alterations 0)
                             (if (memv step changed) (if (negative? fifths) -1/2 1/2) 0))
                    (wmx:fail "nonstandard key signature"))) (iota 7)))
    (let* ((major (modulo (* 7 fifths) 12))
           (pc (modulo (ly:pitch-semitones tonic) 12))
           (mode (cond ((= pc major) "major")
                       ((= pc (modulo (+ major 9) 12)) "minor")
                       (else (wmx:fail "unsupported key mode")))))
      `(key (@ (number ,(wmx:text staff))) ,(wmx:node 'fifths fifths) (mode ,mode)))))

(define (wmx:direction mark staff voice)
  (let* ((name (wmx:name mark))
         (span (wmx:property mark 'span-direction 0))
         (type (case name
                 ((AbsoluteDynamicEvent)
                  (let ((value (wmx:property mark 'text)))
                    (unless (member value '("pppppp" "ppppp" "pppp" "ppp" "pp" "p"
                                             "mp" "mf" "f" "ff" "fff" "ffff" "fffff"
                                             "ffffff" "fp" "sf" "sfz" "sffz" "rfz" "fz"))
                      (wmx:fail "unsupported dynamic ~a" value))
                    `(dynamics (,(string->symbol value)))))
                 ((CrescendoEvent DecrescendoEvent)
                  `(wedge (@ (type ,(if (= span 1) "stop"
                                        (if (eq? name 'CrescendoEvent) "crescendo" "diminuendo"))))))
                 ((SustainEvent) `(pedal (@ (type ,(if (= span 1) "stop" "start")) (line "yes"))))
                 (else (wmx:fail "unsupported direction ~a" name)))))
    `(direction (direction-type ,type) (voice ,voice) ,(wmx:node 'staff staff))))

(define (wmx:notation mark)
  (case (wmx:name mark)
    ((TieEvent AbsoluteDynamicEvent CrescendoEvent DecrescendoEvent SustainEvent BeamEvent) #f)
    ((SlurEvent PhrasingSlurEvent)
     `(slur (@ (type ,(if (= (wmx:property mark 'span-direction) 1) "stop" "start"))
               (number ,(if (eq? (wmx:name mark) 'SlurEvent) "1" "2")))))
    ((ArticulationEvent)
     (let ((type (wmx:text (wmx:property mark 'articulation-type))))
       (cond ((member type '("staccato" "staccatissimo" "tenuto" "accent" "portato"))
              `(articulations (,(string->symbol (if (equal? type "portato") "detached-legato" type)))))
             ((equal? type "marcato") '(articulations (strong-accent)))
             ((member type '("trill" "mordent" "prall" "turn"))
              `(ornaments (,(string->symbol (cond ((equal? type "trill") "trill-mark")
                                                 ((equal? type "prall") "inverted-mordent")
                                                 (else type))))))
             ((equal? type "fermata") '(fermata))
             (else (wmx:fail "unsupported articulation ~a" type)))))
    (else (wmx:fail "unsupported note mark ~a" (wmx:name mark)))))

(define (wmx:part-xml data id measures divisions)
  (let* ((events (car data)) (staves (caddr data))
         (ties (make-hash-table)) (last-note #f))
    (define (ticks value)
      (unless (integer? (* value divisions)) (wmx:fail "non-integral XML duration"))
      (wmx:text (* value divisions)))
    (define (movement kind length) `(,kind (duration ,(ticks length))))
    (define (repeat-node event)
      (let* ((values (vector-ref event 3)) (forward (eq? (car values) 'forward)))
        `(barline (@ (location ,(if forward "left" "right")))
           (repeat (@ (direction ,(symbol->string (car values)))
                      ,@(if forward '() `((times ,(wmx:text (cadr values))))))))))
    (define (note-node event start stop chord)
      (let* ((kind (vector-ref event 2)) (payload (vector-ref event 3))
             (m (car payload)) (marks (cadr payload))
             (staff (vector-ref event 4)) (voice (vector-ref event 5))
             (original (vector-ref event 0)) (end (+ original (vector-ref event 1)))
             (pitch (wmx:property m 'pitch)) (duration (wmx:property m 'duration))
             (rest (eq? kind 'rest))
             (key (and (not rest) (list staff voice (ly:pitch-notename pitch)
                                       (ly:pitch-octave pitch) (ly:pitch-alteration pitch))))
             (pending (and key (hash-ref ties key #f)))
             (tie-stop (and pending (= pending start)))
             (tie-start (and (not rest) (or (< stop end)
                              (any (lambda (a) (eq? (wmx:name a) 'TieEvent)) marks))))
             (tie-types (append (if tie-stop '("stop") '()) (if tie-start '("start") '())))
             (notations (append (map (lambda (t) `(tied (@ (type ,t)))) tie-types)
                           (if (= start original) (filter-map wmx:notation marks) '())))
             (scale (ly:duration-scale duration))
             (log (ly:duration-log duration))
             (unsplit (and (= start original) (= stop end))))
        (when (and pending (not tie-stop)) (wmx:fail "tie does not meet its next note"))
        (when key (if tie-start (hash-set! ties key stop) (hash-remove! ties key)))
        `(note ,@(if chord '((chord)) '())
          ,(if rest '(rest)
               `(pitch (step ,(list-ref '("C" "D" "E" "F" "G" "A" "B") (ly:pitch-notename pitch)))
                 ,@(if (zero? (ly:pitch-alteration pitch)) '()
                       (let ((alter (* 2 (ly:pitch-alteration pitch))))
                         (unless (integer? alter) (wmx:fail "microtonal pitches are not supported yet"))
                         (list (wmx:node 'alter alter))))
                 ,(wmx:node 'octave (+ 4 (ly:pitch-octave pitch)))))
          (duration ,(ticks (- stop start)))
          ,@(map (lambda (t) `(tie (@ (type ,t)))) tie-types)
          (voice ,voice)
          ,@(if (and unsplit (<= -1 log 10))
                (append (list `(type ,(list-ref '("breve" "whole" "half" "quarter" "eighth" "16th" "32nd" "64th" "128th" "256th" "512th" "1024th") (+ log 1))))
                        (map (lambda (_) '(dot)) (iota (ly:duration-dot-count duration)))) '())
          ,@(if (and unsplit (not (= scale 1)))
                `((time-modification ,(wmx:node 'actual-notes (denominator scale))
                                      ,(wmx:node 'normal-notes (numerator scale)))) '())
          ,(wmx:node 'staff staff)
          ,@(if (null? notations) '() (list (cons 'notations notations))))))
    (define (measure-xml bar index)
      (let* ((start (car bar)) (end (cadr bar)) (meter (caddr bar))
             (inside (filter (lambda (e) (and (<= start (vector-ref e 0))
                                             (or (< (vector-ref e 0) end)
                                                 (and (= index (length measures))
                                                      (= (vector-ref e 0) end)
                                                      (zero? (vector-ref e 1)))))) events))
             (notes (filter (lambda (e) (and (memq (vector-ref e 2) '(note rest skip))
                                              (< (vector-ref e 0) end)
                                              (> (+ (vector-ref e 0) (vector-ref e 1)) start))) events))
             (output '()) (cursor start))
        (define (put node) (set! output (cons node output)))
        (define (seek pos)
          (cond ((> pos cursor) (put (movement 'forward (- pos cursor))))
                ((< pos cursor) (put (movement 'backup (- cursor pos)))))
          (set! cursor pos) (set! last-note #f))
        (put `(attributes (divisions ,(wmx:text divisions))
                 (time ,(wmx:node 'beats (car meter)) ,(wmx:node 'beat-type (cdr meter)))
                 ,@(if (> staves 1) (list (wmx:node 'staves staves)) '())))
        (for-each
          (lambda (e)
            (let ((kind (vector-ref e 2)) (m (vector-ref e 3)) (staff (vector-ref e 4)))
              (case kind
                ((KeyChangeEvent) (seek (vector-ref e 0)) (put `(attributes ,(wmx:key m staff))))
                ((clef)
                 (seek (vector-ref e 0))
                 (let ((clef (assoc (car m) '(("clefs.G" . "G") ("clefs.F" . "F") ("clefs.C" . "C")))))
                   (unless clef (wmx:fail "unsupported clef ~a" m))
                   (unless (and (integer? (cdr m)) (<= 1 (cdr m) 5))
                     (wmx:fail "unsupported clef line"))
                   (put `(attributes (clef (@ (number ,(wmx:text staff)))
                                           (sign ,(cdr clef)) ,(wmx:node 'line (cdr m)))))))
                ((TempoChangeEvent)
                 (let ((count (wmx:property m 'metronome-count))
                       (unit (wmx:property m 'tempo-unit)))
                   (unless (and (number? count) (> count 0) (ly:duration? unit))
                     (wmx:fail "tempo needs one positive metronome value"))
                   (seek (vector-ref e 0))
                   (put `(direction (direction-type (words "Tempo"))
                             (sound (@ (tempo ,(wmx:text (exact->inexact (* count (wmx:quarters unit)))))))))))
                ((direction)
                 (seek (vector-ref e 0)) (put (wmx:direction m staff (vector-ref e 5))))))) inside)
        (for-each
          (lambda (e)
            (let* ((pos (max start (vector-ref e 0)))
                   (stop (min end (+ (vector-ref e 0) (vector-ref e 1))))
                   (kind (vector-ref e 2))
                   (identity (list pos stop (vector-ref e 4) (vector-ref e 5)))
                   (chord (and (eq? kind 'note) (equal? identity last-note))))
              (unless chord (seek pos))
              (if (eq? kind 'skip) (put (movement 'forward (- stop pos)))
                  (let ((marks (cadr (vector-ref e 3))))
                    (when (and (= pos (vector-ref e 0)) (not chord))
                      (for-each (lambda (m)
                                  (when (memq (wmx:name m) '(AbsoluteDynamicEvent CrescendoEvent DecrescendoEvent SustainEvent))
                                    (put (wmx:direction m (vector-ref e 4) (vector-ref e 5))))) marks))
                    (put (note-node e pos stop chord))))
              (set! cursor stop)
              (set! last-note (and (eq? kind 'note) identity)))) notes)
        (seek end)
        (let ((repeats (delete-duplicates
                        (filter (lambda (e)
                                  (and (eq? (vector-ref e 2) 'repeat)
                                       (or (and (= start (vector-ref e 0)) (eq? (car (vector-ref e 3)) 'forward))
                                           (and (= end (vector-ref e 0)) (eq? (car (vector-ref e 3)) 'backward))))) events)
                        (lambda (a b) (equal? (vector-ref a 3) (vector-ref b 3))))))
          `(measure (@ (number ,(wmx:text index))
                       ,@(if (cadddr bar) '((implicit "yes")) '()))
             ,@(map repeat-node (filter (lambda (e) (eq? (car (vector-ref e 3)) 'forward)) repeats))
             ,@(reverse output)
             ,@(map repeat-node (filter (lambda (e) (eq? (car (vector-ref e 3)) 'backward)) repeats))))))
    (let ((result `(part (@ (id ,id)) ,@(map measure-xml measures (iota (length measures) 1)))))
      (unless (zero? (hash-count (const #t) ties)) (wmx:fail "unterminated tie"))
      result)))

(define (wmx:document music)
  (let* ((parts (wmx:parts music))
         (data (map wmx:collect (if (null? parts) (list music) parts)))
         (events (stable-sort (append-map car data) (lambda (a b) (< (vector-ref a 0) (vector-ref b 0)))))
         (end (apply max (map cadr data)))
         (measures (wmx:measures events end))
         (divisions (fold (lambda (e n) (lcm n (denominator (vector-ref e 0))
                                                (denominator (vector-ref e 1))))
                          (fold (lambda (bar n) (lcm n (denominator (car bar))
                                                       (denominator (cadr bar)))) 1 measures)
                          events))
         (ids (map (lambda (n) (format #f "P~a" n)) (iota (length data) 1))))
    (when (or (zero? end) (null? measures)) (wmx:fail "score has no timed music"))
    (when (> (* end divisions) 2147483647) (wmx:fail "duration divisions exceed the supported range"))
    (for-each (lambda (e)
                (when (and (eq? (vector-ref e 2) 'repeat)
                           (not (member (vector-ref e 0) (cons end (map car measures)))))
                  (wmx:fail "repeat boundary lies inside a measure"))) events)
    `(score-partwise (@ (version "4.0"))
       (part-list ,@(map (lambda (id) `(score-part (@ (id ,id)) (part-name ,id))) ids))
       ,@(map (lambda (part id) (wmx:part-xml part id measures divisions)) data ids))))

(define (wmx:export-book book)
  (for-each
    (lambda (score)
      (when (ly:score? score)
        (let* ((document (wmx:document (ly:score-music score)))
               (suffix (if (zero? wmx:score-index) "" (format #f "-~a" wmx:score-index)))
               (path (string-append (ly:parser-output-name) suffix ".musicxml")))
          ;; Validate and serialize before opening the destination.
          (let ((xml (call-with-output-string
                       (lambda (port)
                         (display "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n" port)
                         (sxml->xml document port)))))
            (call-with-output-file path (lambda (port) (display xml port))))
          (set! wmx:score-index (+ wmx:score-index 1)))))
    (reverse (ly:book-scores book)))
  (for-each wmx:export-book (reverse (ly:book-book-parts book))))
